services:
  postgres:
    image: postgres:16
    container_name: dragon-postgres
    environment:
      POSTGRES_DB: dragon_of_north
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: version
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-test
    container_name: dragon-backend
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dragon_of_north
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: version
    ports:
      - "8080:8080"
